server:
  port: 9090

spring:
  application:
    name: order-service
    
eureka:
  instance:
    hostname: localhost
    metadata-map:
      version: current
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka