server:
  port: 8083
  
spring:
  application:
    name: wms-service
          
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 1
    instance-info-replication-interval-seconds: 1

ribbon:
  eager-load:
    enabled: true

feign:
  hystrix:
    enabled: false